### ISSUE TITLE
HTTP 410 when playing any song from spotify?

### ISSUE THREAD

**Issue by mitchellurgero** [L0SER8228/discord-player-bot#54]
Getting a 410 error when playing a song from spotify, I suspect an API rate limit but wanted to see if there was a way around it?

**Comment by mitchellurgero** [comment]
Thanks for the reply man! Sadly it was happening with any song (I should have specified this in my original post)

Long story short, I was getting throttled by YouTube (410 and then later 429) - so I am using the bot over a VPN that changes IP frequently and it's fine again.

**Comment by L0SER8228** [comment]
You have to use YouTube cookie. Though it'll not fix the issue completely, but it's still better.

https://discord-player.js.org/docs/guides/cookies

**Comment by mitchellurgero** [comment]
yeah cookie is an option but I don't wanna use my personal account on it - vpn has been solid. No more rate limits lol Thanks for the help!
